FROM mcr.microsoft.com/devcontainers/go:1-1.22-bookworm

ARG NODE_VERSION=20

RUN curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash - \
    && apt-get install -y nodejs

RUN npm install -g typescript